[env]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
build_unflags = -std=gnu++11
build_flags =
    -std=gnu++17
    -DCORE_DEBUG_LEVEL=3
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

[env:esp32-c3-devkitm-1]
build_src_filter =
    +<*>
    -<debug/>
lib_deps =
    olikraus/U8g2@^2.36.5
    bblanchon/ArduinoJson@^7.0.4
    tzapu/WiFiManager@^2.0.17
    paulstoffregen/OneWire@^2.3.8
    milesburton/DallasTemperature@^4.0.4
    sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library@^1.1.2

[env:esp32-c3-debug-button]
build_type = debug
build_src_filter =
    +<debug/button_debug_main.cpp>
    +<drivers/ButtonInput.cpp>

[env:esp32-c3-debug-gsr]
build_type = debug
build_src_filter =
    +<debug/gsr_debug_main.cpp>
    +<drivers/GsrSensor.cpp>

[env:esp32-c3-debug-ds18b20]
build_type = debug
build_src_filter =
    +<debug/ds18b20_debug_main.cpp>
    +<drivers/Ds18b20Sensor.cpp>
lib_deps =
    paulstoffregen/OneWire@^2.3.8
    milesburton/DallasTemperature@^4.0.4

[env:esp32-c3-debug-hx710b]
build_type = debug
build_src_filter =
    +<debug/hx710b_debug_main.cpp>
    +<drivers/Hx710bSensor.cpp>

[env:esp32-c3-debug-bp]
build_type = debug
build_src_filter =
    +<debug/bp_debug_main.cpp>
    +<drivers/Hx710bSensor.cpp>
    +<drivers/PneumaticController.cpp>

[env:esp32-c3-debug-max30102]
build_type = debug
build_src_filter =
    +<debug/max30102_debug_main.cpp>
    +<drivers/Max30102Sensor.cpp>
lib_deps =
    sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library@^1.1.2

[env:esp32-c3-debug-backend]
build_type = debug
build_flags =
    ${env.build_flags}
build_src_filter =
    +<debug/backend_debug_main.cpp>
    +<network/ApiClient.cpp>
    +<network/WiFiService.cpp>
    +<utils/TimeUtils.cpp>
lib_deps =
    bblanchon/ArduinoJson@^7.0.4
    tzapu/WiFiManager@^2.0.17
